interface WayfairEnvBindings {
  DB: D1Database;
  FILES: R2Bucket;
  DATABASE_URL?: string;
  DATABASE_POOL_MAX?: string;
  APP_ORIGIN?: string;
  CRON_SECRET?: string;
  APP_ACCESS_USER?: string;
  APP_ACCESS_PASSWORD?: string;
  CATALOG_SYNC_PAGE_BUDGET?: string;
  CATALOG_MANUAL_SYNC_PAGE_BUDGET?: string;
  CATALOG_SYNC_PAGE_DELAY_MS?: string;
  S3_BUCKET?: string;
  S3_REGION?: string;
  S3_ENDPOINT?: string;
  S3_FORCE_PATH_STYLE?: string;
  S3_ACCESS_KEY_ID?: string;
  S3_SECRET_ACCESS_KEY?: string;
  S3_USE_DEFAULT_CREDENTIAL_CHAIN?: string;
  MICROSOFT_TENANT_ID?: string;
  MICROSOFT_CLIENT_ID?: string;
  MICROSOFT_CLIENT_SECRET?: string;
  MICROSOFT_REFRESH_TOKEN?: string;
  OUTLOOK_MAILBOX_USER?: string;
  OUTLOOK_MANUAL_SYNC_LOOKBACK_DAYS?: string;
  WAYFAIR_AD_CLIENT_ID?: string;
  WAYFAIR_AD_CLIENT_SECRET?: string;
  WAYFAIR_OPS_CLIENT_ID?: string;
  WAYFAIR_OPS_CLIENT_SECRET?: string;
  WAYFAIR_CATALOG_CLIENT_ID?: string;
  WAYFAIR_CATALOG_CLIENT_SECRET?: string;
  WAYFAIR_CATALOG_SUPPLIER_ID?: string;
  WAYFAIR_PRODUCT_ADDITION_CLIENT_ID?: string;
  WAYFAIR_PRODUCT_ADDITION_CLIENT_SECRET?: string;
  WAYFAIR_PRODUCT_ADDITION_SUPPLIER_ID?: string;
  WAYFAIR_DEPLOYMENT_ENV?: string;
  WAYFAIR_EXPECTED_SUPPLIER_IDS?: string;
  ALLOW_WAYFAIR_AD_LIVE_CHANGES?: string;
  ALLOW_WAYFAIR_LIVE_PUSH?: string;
  ALLOW_WAYFAIR_PRODUCT_ADDITION_LIVE_SUBMIT?: string;
  OUTLOOK_INGEST_TOKEN?: string;
  FEISHU_APP_ID?: string;
  FEISHU_APP_SECRET?: string;
  FEISHU_BITABLE_APP_TOKEN?: string;
  FEISHU_BITABLE_TABLE_ID?: string;
  LINGXING_APP_ID?: string;
  LINGXING_APP_SECRET?: string;
  LINGXING_API_BASE?: string;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface Env extends WayfairEnvBindings {}
