const MAX_REPORT_SIZE=20*1024*1024;
const ALLOWED_TYPES=new Set(["text/html","application/pdf","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]);

async function bindings(){return (await import("cloudflare:workers")).env;}

async function ensure(db:D1Database){await db.prepare("CREATE TABLE IF NOT EXISTS report_uploads (id TEXT PRIMARY KEY NOT NULL, file_name TEXT NOT NULL, title TEXT NOT NULL, kind TEXT NOT NULL, content_type TEXT NOT NULL, object_key TEXT NOT NULL, created_at TEXT NOT NULL)").run();}

export async function GET(){try{const env=await bindings();await ensure(env.DB);const rows=await env.DB.prepare("SELECT id,file_name AS fileName,title,kind,content_type AS contentType,created_at AS createdAt FROM report_uploads ORDER BY created_at DESC").all();return Response.json({reports:rows.results||[]});}catch(error){return Response.json({error:error instanceof Error?error.message:"补充报告读取失败"},{status:500});}}

export async function POST(request:Request){try{const env=await bindings();await ensure(env.DB);const form=await request.formData();const file=form.get("file");if(!(file instanceof File))return Response.json({error:"请选择报告文件"},{status:400});if(!file.size||file.size>MAX_REPORT_SIZE)return Response.json({error:"报告文件为空或超过20MB"},{status:400});const extension=file.name.toLowerCase().split('.').pop();const inferred=extension==='html'||extension==='htm'?"text/html":extension==='pdf'?"application/pdf":extension==='xlsx'?"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":"";const contentType=ALLOWED_TYPES.has(file.type)?file.type:inferred;if(!ALLOWED_TYPES.has(contentType))return Response.json({error:"仅支持HTML、PDF或XLSX报告"},{status:400});const id=crypto.randomUUID();const safeName=file.name.replace(/[^\p{L}\p{N}_. -]/gu,"_").slice(0,160);const objectKey=`reports/${id}/${safeName}`;await env.FILES.put(objectKey,file.stream(),{httpMetadata:{contentType}});const title=safeName.replace(/\.(html?|pdf|xlsx)$/i,"");const kind=contentType==="application/pdf"?"PDF":contentType==="text/html"?"补充报告":"表格";const createdAt=new Date().toISOString();await env.DB.prepare("INSERT INTO report_uploads(id,file_name,title,kind,content_type,object_key,created_at) VALUES(?,?,?,?,?,?,?)").bind(id,safeName,title,kind,contentType,objectKey,createdAt).run();return Response.json({id,fileName:safeName,title,kind,contentType,createdAt});}catch(error){return Response.json({error:error instanceof Error?error.message:"报告上传失败"},{status:500});}}

export async function DELETE(request:Request){try{const env=await bindings();await ensure(env.DB);const id=new URL(request.url).searchParams.get("id");if(!id)return Response.json({error:"缺少报告id"},{status:400});const row=await env.DB.prepare("SELECT object_key FROM report_uploads WHERE id=?").bind(id).first<{object_key:string}>();if(!row)return Response.json({error:"报告不存在"},{status:404});await env.FILES.delete(row.object_key);await env.DB.prepare("DELETE FROM report_uploads WHERE id=?").bind(id).run();return Response.json({deleted:true,id});}catch(error){return Response.json({error:error instanceof Error?error.message:"报告删除失败"},{status:500});}}
